<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Meta\Conversion\Block\Pixel\Purchase;

/**
 * @var Purchase $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

if ($block->getFacebookPixelID()) {
    $config = [
        'url' => $block->getTrackerUrl(),
        'payload' => [
            'eventName' => $block->getEventToObserveName(),
            'lastOrder' => $block->getLastOrderRealOrderEntityId(),
            'eventId' => $block->getEventId(),
        ],
        'browserEventData' => [
            'fbAgentVersion' => $block->getFacebookAgentVersion(),
            'fbPixelId' => $block->getFacebookPixelID(),
            'source' => $block->getSource(),
            'pluginVersion' => $block->getPluginVersion(),
            'track' => 'trackCustom',
            'event' => 'Purchase',
            'payload' => [
                'content_type' => $block->getContentType(),
                'content_ids' => $block->getContentIDs(),
                'num_items' => $block->getNumItems(),
                'contents' => $block->getContents(),
                'content_name' => $block->getContentName(),
                'value' => $block->getValue(),
                'currency' => strtolower((string)$block->getCurrency()),
                'order_id' => $block->getLastOrderRealOrderEntityId(),
            ],
        ],
    ];
    $json = json_encode($config, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT);
    $script = "(function run(){if(!window.merlinMetaHyva){window.setTimeout(run,10);return;}window.merlinMetaHyva.track({$json});}());";
    echo $secureRenderer->renderTag('script', ['type' => 'text/javascript'], $script, false);
}
